# fly.toml app configuration file generated for deploy-fastapi-flyio on 2023-07-27T20:09:52+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "deploy-fastapi-flyio"
primary_region = "syd"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
