---
name: climate-change-api
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
        working-directory: ./earthquakes-nz
      - run: kaggle datasets download kkhandekar/earthquakes-data-nz
      - run: unzip earthquakes-data-nz.zip
        working-directory: ./earthquakes-nz
      - run: pytest .
        working-directory: ./earthquakes-nz
